"use strict";
var AuthRoutes = require("./modules/auth/auth.routes");
var AuthorsRoutes = require("./modules/authors/authors.routes");
var CategoriesRoutes = require("./modules/categories/categories.routes");
var MetadataRoutes = require("./modules/metadata/metadata.routes");
var ProductsRoutes = require("./modules/products/products.routes");
var TagsRoutes = require("./modules/tags/tags.routes");
var MembersRoutes = require("./modules/members/members.routes");
var BlogRoutes = require("./modules/blog/blog.routes");
var EmailRoutes = require("./modules/email/email.routes");
var MessagesRoutes = require("./modules/messages/messages.routes");
module.exports = [].concat(AuthRoutes, AuthorsRoutes, CategoriesRoutes, MetadataRoutes, ProductsRoutes, TagsRoutes, MembersRoutes, BlogRoutes, EmailRoutes, MessagesRoutes);
